### ISSUE TITLE
Clip features prior to reproject

### ISSUE THREAD

**Issue by rclark** [mapbox/node-wmshp#4]
If features are at / cross the poles ogr can fail to reproject them. We should clip the features to ±85.05113° before reprojecting them. This might be somewhat complicated by the fact that we don't know the incoming coordinate system. Not sure how to do this yet via node-gdal.

cc @BergWerkGIS

**Comment by wilhelmberg** [comment]
> This might be somewhat complicated by the fact that we don't know the incoming coordinate system

Shapefiles should have a `prj` attached.
If they don't we should throw an error.
A quick look at node-gdal api didn't show any property that exposes SRS. (Maybe I've missed it).

> Not sure how to do this yet via node-gdal.

A starting point might be `executeSQL` with a `spatial_filter` set or passing [`ST_Intersection`](http://www.gaia-gis.it/spatialite-2.4.0-4/spatialite-sql-2.4-4.html#p14) with `dialect=sqlite` directly with the `statement`parameter to 
http://naturalatlas.github.io/node-gdal/classes/gdal.Dataset.html?#method-executeSQL

**Comment by wilhelmberg** [comment]
> This might be somewhat complicated by the fact that we don't know the incoming coordinate system

Overlooked, [`srs`](http://naturalatlas.github.io/node-gdal/classes/gdal.Layer.html#attr-srs) is a property of [gdal.Layer](http://naturalatlas.github.io/node-gdal/classes/gdal.Layer.html)
